---
- name: Disable Wi-Fi adapter on Windows machines
  hosts: 10.11.0.118  # Change this to your target group
  gather_facts: false
  tasks:
    - name: Disable the Wi-Fi network adapter using PowerShell
      ansible.windows.win_shell: |
        Disable-NetAdapter -Name "Wi-Fi" -Confirm:$false
      register: disable_result
      # Only run this task if the command succeeds (which it should)
      # or if the adapter is already disabled (which will produce a non-zero exit code if not suppressed)
      # We suppress the confirmation prompt using -Confirm:$false

    - name: Display the result of the disable command
      ansible.builtin.debug:
        var: disable_result.stdout_lines
