---
- name: Set lock screen wallpaper same as desktop wallpaper
  hosts: windows
  tasks:
    - name: Set desktop wallpaper
      win_command: powershell.exe -Command "Add-Type -AssemblyName 'PresentationFramework'; [System.Windows.Forms.SendKeys]::SendWait('%W'); Start-Sleep -Seconds 1; [System.Windows.Forms.SendKeys]::SendWait('{ENTER}'); Start-Sleep -Seconds 1"
      args:
        stdin: |
          Set-ItemProperty -Path 'HKCU:\Control Panel\Desktop\' -Name Wallpaper -Value 'C:\Windows\Web\Wallpaper\Windows\img0.jpg'
          Set-ItemProperty -Path 'HKCU:\Control Panel\Desktop\' -Name WallpaperStyle -Value 2
          Set-ItemProperty -Path 'HKCU:\Control Panel\Personalization\' -Name LockScreenImage -Value 'C:\Windows\Web\Wallpaper\Windows\img0.jpg'
    - name: Refresh user policies
      ansible.windows.win_shell: gpupdate /force


