---
- name: Set login screen wallpaper to match desktop wallpaper
  hosts: windows
    #  become: true
  tasks:
    - name: Set the desktop wallpaper
      win_regedit:
        path: HKCU:\Control Panel\Desktop
        name: Wallpaper
        data: 'C:\Windows\Web\Wallpaper\Windows\img0.jpg'  # Path to the wallpaper image
        state: present

    - name: Set the login screen wallpaper (Windows 10+)
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization
        name: LockScreenImage
        data: 'C:\Windows\Web\Wallpaper\Windows\img0.jpg'  # Same path as desktop wallpaper
        state: present
        type: string

    - name: Force Windows to apply the wallpaper changes
      win_shell: |
        RUNDLL32.EXE user32.dll,UpdatePerUserSystemParameters

