- name: Send message to Windows hosts
  hosts: 10.11.0.119
  gather_facts: no
  tasks:
    - name: Send popup message using msg.exe
      win_shell: |
        msg * "This is a message sent from Ansible."

