---
- name: Set default boot to Windows in dual-boot system
  hosts: 10.11.0.231
  become: true

  tasks:
    - name: Find the Windows boot entry in GRUB
      command: grep -i 'Windows' /boot/grub/grub.cfg
      register: windows_boot_entry
      changed_when: false
      failed_when: false

    - name: Set GRUB_DEFAULT to the Windows entry
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_DEFAULT='
        line: "GRUB_DEFAULT='{{ windows_boot_entry.stdout | regex_replace('^.*menuentry ', '') | regex_replace('\"$', '') }}'"
      notify:
        - update-grub

    - name: Update GRUB configuration
      command: update-grub
      when: windows_boot_entry.stdout != ""
      notify:
        - reboot system

  handlers:
    - name: update-grub
      command: update-grub

    - name: reboot system
      reboot:
        msg: "Rebooting after changing default boot entry to Windows."
        connect_timeout: 5
        reboot_timeout: 600
        test_command: whoami

