---
- name: Delete multiple users from Ubuntu system
  hosts: linux
  become: yes
  tasks:
    - name: Remove user accounts
      user:
        name: "{{ item }}"
        state: absent
        remove: yes
      loop:
        - student
        - fde 
        
      # Optionally, you can specify the 'remove' flag to delete their home directories
      # This line is optional depending on whether you want to remove home directories.
 
