---
- name: Disable Google Authenticator for Ubuntu login screen
  hosts: linuxtest
  become: true
  tasks:
    - name: Comment out pam_google_authenticator.so in /etc/pam.d/common-auth
      lineinfile:
        path: /etc/pam.d/common-auth
        regexp: '^auth\s+required\s+pam_google_authenticator.so'
        line: '#auth required pam_google_authenticator.so'
        state: present
        backrefs: yes

    - name: Ensure SSH service is restarted (if needed, for SSH-related changes)
      service:
        name: sshd
        state: restarted
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Restart the systemd service to apply PAM changes (if needed for GUI login)
      command: systemctl restart display-manager
      when: ansible_facts['distribution'] == 'Ubuntu'

