---
- name: Add a user with sudo privileges
  hosts: 10.11.0.219 
  become: yes
  vars:
    username: fds
    password: "{{ 'cse' | password_hash('sha512') }}"
  tasks:
    - name: Add user
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password }}"
        shell: /bin/bash

    - name: Add user to sudo group
      ansible.builtin.user:
        name: "{{ username }}"
        groups: sudo
        append: yes

    - name: Allow passwordless sudo for user
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^{{ username }} ALL=\(ALL:ALL\) NOPASSWD:ALL'
        line: '{{ username }} ALL=(ALL:ALL) NOPASSWD:ALL'

